apiVersion: v1
kind: Secret
metadata:
  name: encrypted-volume
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Pa22word"
  CRYPTO_KEY_PROVIDER: "secret"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: encrypted-volume
  namespace: longhorn-system
spec:
  storageClassName: "longhorn-encrypted"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi