---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/longhorn/crd
    - /fleet/longhorn
    - /fleet/longhorn/config
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/neuvector/crd
    - /fleet/neuvector
    - /fleet/neuvector/config
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring
    - /fleet/rancher-monitoring/crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/logging
    - /fleet/logging/crd
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harbor
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/harbor
  targets:
  - name: harbor
    clusterSelector:
      matchLabels:
        harbor: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-backup
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/rancher-backup
    - /fleet/rancher-backup/crd
  targets:
  - name: rancher-backup
    clusterSelector:
      matchLabels:
        backups: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: keycloak
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/keycloak
  targets:
  - name: keycloak
    clusterSelector:
      matchLabels:
        keycloak: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: nexus
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/nexus
    - /fleet/nexus/config
  targets:
  - name: nexus
    clusterSelector:
      matchLabels:
        nexus: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: minio
  namespace: fleet-local
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/minio
  targets:
  - name: minio
    clusterSelector:
      matchLabels:
        minio: enabled