apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-configs
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/longhorn-configs
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/neuvector
    - /fleet/neuvector/crd
    - /fleet/neuvector/config
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring
    - /fleet/rancher-monitoring-crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harbor
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/harbor
  targets:
  - name: harbor
    clusterSelector:
      matchLabels:
        harbor: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-backup
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/rancher-backup
    - /fleet/rancher-backup/crd
  targets:
  - name: rancher-backup
    clusterSelector:
      matchLabels:
        backups: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: keycloak
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  paths:
    - /fleet/keycloak
  targets:
  - name: keycloak
    clusterSelector:
      matchLabels:
        keycloak: enabled