---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/longhorn/crd
    - /fleet/longhorn
    - /fleet/longhorn/config
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://git.homelab.lan/nnewc/fleet.git
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/neuvector/crd
    - /fleet/neuvector
    - /fleet/neuvector/config
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/rancher-monitoring
    - /fleet/rancher-monitoring-crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harbor
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/harbor
  targets:
  - name: harbor
    clusterSelector:
      matchLabels:
        harbor: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-backup
  namespace: fleet-default
spec:
  repo: https://git.homelab.lan/nnewc/fleet.git
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/rancher-backup
    - /fleet/rancher-backup/crd
  targets:
  - name: rancher-backup
    clusterSelector:
      matchLabels:
        backups: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: keycloak
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/keycloak
  targets:
  - name: keycloak
    clusterSelector:
      matchLabels:
        keycloak: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  repo: https://github.com/nnewc/fleet
  branch: main
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lSQVBzeGNnbUZsck4wcThjN3prcjJ4Zjh3Q2dZSUtvWkl6ajBFQXdJd0xERVEKTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZTUJZR0ExVUVBeE1QVkdWdGNHVnpkQ0JTYjI5MElFTkJNQjRYRFRJMQpNRE14TXpBME1Ea3hORm9YRFRNMU1ETXhNVEEwTURreE5Gb3dMREVRTUE0R0ExVUVDaE1IVkdWdGNHVnpkREVZCk1CWUdBMVVFQXhNUFZHVnRjR1Z6ZENCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRUkrb2laNXZXbWhIOUxtYmNpUjNZWjAvR1duNHN2RVBhMm4wUkxtRG1YNFV1Q3M1L1lCU21jVGN0UldXMgpRK2hVYzRXWlZISXQzWlpyd1RLL3JrVHRtS05GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUVGTEtVWXA4ZXJUQzJqSHBtbDcxczNjZWsyOGw5TUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lIWDc1VjgzQjZyc1dxRExuUnAyRCt3MGI0Y3lDb0ZZSUVRNDR1a1M1ekg1QWlBWQpyaGNmcDcwcGE2K3pRRVdUZy9GcmYvVG9WVzg4T2RYR2VKVUFQdVFwREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  paths:
    - /fleet/cert-manager
  targets:
  - name: cert-manager
    clusterSelector:
      matchLabels:
        cert-manager: enabled