ingress:
  enabled: true
  hosts:
  - nexus.192-168-60-101.nip.io
  # annotations: 
  #   cert-manager.io/issuer: selfsigned-issuer
  # tls:
  # - hosts:
  #   - nexus.192-168-60-101.nip.io
  #   secretName: nexus-ingress
persistence:
  enabled: true
  storageClass: longhorn
rootPassword:
  secret: admin-creds