controller:
  apisvc:
    type: ClusterIP
  configmap:
    data:
      sysinitcfg.yaml: |
        Scanner_Autoscale:
        Strategy: delayed
        Min_Pods: 1
        Max_Pods: 3
    enabled: true
  replicas: 1
  disruptionBudget: 2
  pvc:
    enabled: true
    storageClass: longhorn
  ranchersso:
    enabled: true
  runAsUser: 1000
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
global:
  cattle:
    url: https://rancher.10.7.2.230.nip.io
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock
manager:
  enabled: true
  svc:
    type: ClusterIP
  runAsUser: 5400
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
  ingress:
    enabled: true
    annotations:
        cert-manager.io/issuer: selfsigned-issuer
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    host: neuvector-manager.10.7.2.230.nip.io
    secretName: manager-ingress
    tls: true
enforcer:
  enabled: false
  runAsUser: 1000
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
cve:
  adapter:
    enabled: true
    ingress:
      enabled: false
      annotations:
        cert-manager.io/issuer: selfsigned-issuer
      host: neuvector-adapter.10.7.2.230.nip.io
      path: "/"
      secretName: adapter-ingress
      tls: true
    runAsUser: 1000
    svc:
      type: ClusterIP
    harbor:
      secretName: harbor-credentials
    certificate:
      secret: adapter-tls-cert
      pemFile: tls.crt
  scanner:
    runAsUser: 5400
    resources:
    requests:
      cpu: "500m"
      memory: "100Mi"
  updater:
    runAsUser: 1000
rbac: true
leastPrivilege: true