controller:
  pvc:
    enabled: false
  ranchersso:
    enabled: true
  runAsUser: 1000
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
global:
  cattle:
    url: https://10.7.2.98.nip.io
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock
manager:
  svc:
    type: ClusterIP
  runAsUser: 5400
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
enforcer:
  runAsUser: 1000
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
cve:
  adapter:
    enabled: true
    runAsUser: 1000
    svc:
      type: NodePort
    harbor:
      secretName: adapter-credentials
  scanner:
    runAsUser: 5400
    resources:
    requests:
      cpu: "500m"
      memory: "100Mi"
  updater:
    runAsUser: 1000
rbac: true
leastPrivilege: true
