ingress:
  enabled: true
  rules:
  - host: keycloak.10.7.2.98.nip.io
    paths:
    - path: /
      pathType: Prefix
  annotations: 
    cert-manager.io/issuer: selfsigned-cluster-issuer
  tls:
  - hosts:
    - keycloak.10.7.2.98.nip.io
    secretName: keycloak-ingress
    annotations: 
      cert-manager.io/issuer: selfsigned-cluster-issuer
    tls:
    - hosts:
      - keycloak.10.7.2.98.nip.io
      secretName: keycloak-ingress-console
postgresql:
  enabled: true
  global:
    storageClass: longhorn
extraEnv: |
  - name: KEYCLOAK_USER
    value: "admin"
  - name: KEYCLOAK_PASSWORD
    value: "changeme"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"