persistence:
  enabled: true
expose:
  type: ingress
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: '0'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      cert-manager.io/issuer: selfsigned-issuer
    hosts: 
      core: harbor.192-168-60-101.nip.io
  tls:
    certSource: secret
    enabled: true
    secret:
      secretName: tls-ingress-harbor
externalURL: https://harbor.192-168-60-101.nip.io      
